apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: o3db
  namespace: project-c13
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 2 #副本数
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest